# Generated by Django 4.2.11 on 2026-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetupload",
            name="column_names",
            field=models.JSONField(
                blank=True,
                help_text="List of column names extracted from the dataset",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datasetupload",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error message if normalization failed", null=True
            ),
        ),
        migrations.AddField(
            model_name="datasetupload",
            name="parquet_file_path",
            field=models.CharField(
                blank=True,
                help_text="Relative path to the normalized Parquet file",
                max_length=512,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="datasetupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADING", "UPLOADING"),
                    ("CONVERTING", "CONVERTING"),
                    ("READY", "READY"),
                    ("FAILED", "FAILED"),
                ],
                default="UPLOADING",
                max_length=16,
            ),
        ),
    ]
