# Generated by Django 4.2.11 on 2026-06-28 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        help_text="Current processing state",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        default=0.0, help_text="Task progress percentage (0.0 to 100.0)"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery async task identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Failure explanation if status is FAILED",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        help_text="The uploaded dataset being processed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="uploads.datasetupload",
                    ),
                ),
            ],
        ),
    ]
