# Generated by Django 4.2.11 on 2026-06-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_processingjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="output_file_path",
            field=models.CharField(
                blank=True,
                help_text="Relative path to full processed output file",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="preview_file_path",
            field=models.CharField(
                blank=True,
                help_text="Relative path to 1000-row preview JSON file",
                max_length=1024,
                null=True,
            ),
        ),
    ]
