# Generated by Django 4.2.11 on 2026-06-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_processingjob_dataset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="generated_regexes",
            field=models.JSONField(
                blank=True,
                help_text="Per-column regexes: list of {column, regex} dicts",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="nl_prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Natural language prompt describing the desired transformation",
            ),
        ),
        migrations.AddField(
            model_name="processingjob",
            name="transformations",
            field=models.JSONField(
                default=list,
                help_text="Triage output: list of {column, nl_pattern, replacement} dicts",
            ),
        ),
    ]
