# Generated by Django 4.2.11 on 2026-07-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_processingjob_generated_regexes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "QUEUED"),
                    ("RUNNING", "RUNNING"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="QUEUED",
                max_length=32,
            ),
        ),
    ]
